version: "3"
services:
  redis-stack:
    hostname: redis-stack
    container_name: redis-stack
    restart: always
    image: redis/redis-stack-server:7.4.0-v0
    logging:
      driver: "none"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6380:6379"
    volumes:
      - /data/ouyucheng/redis-stack/data:/data
      - /data/ouyucheng/redis-stack/config/redis-stack.conf:/etc/redis-stack.conf
    command: redis-server /etc/redis-stack.conf  # ğŸ‘ˆ æ·»åŠ è¿™è¡Œï¼ŒæŒ‡å®šé…ç½®æ–‡ä»¶
    networks:
      - net-xsm-redis-stack
 
networks:
  net-xsm-redis-stack:
    driver: bridge