version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-server
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: testdb
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data/db
      - ./log:/var/log/mongodb
    restart: always
    networks:
      - mongodb-network
networks:
  mongodb-network:
    driver: bridge
