global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kaleido-ai'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'kaleido-ai:9020'
        labels:
          app: 'kaleido-ai'
