spring:
  application:
    name: langchain4j-demo
    version: @kaleido.version@
  profiles:
    active: dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 11
      ssl:
        enabled: true
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: ${REDIS_PASSWORD}
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://${REDIS_HOST}:${REDIS_PORT}"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 11
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.client.codec.StringCodec> {}
        transportMode: "NIO"

# 服务器配置
server:
  # 服务端口：langchain4j 版本运行在 9022 端口
  port: 9023
  servlet:
    # 上下文路径：所有API的前缀路径
    context-path: /kaleido-ai

langchain4j:
  open-ai:
    chat-model:
      api-key: ${AI_API_KEY}
      base-url: ${AI_BASE_URL}
      model-name: ${CHAT_MODEL}
    streaming-chat-model:
      api-key: ${AI_API_KEY}
      base-url: ${AI_BASE_URL}
      model-name: ${CHAT_MODEL}
    embedding-model:
      api-key: ${AI_API_KEY}
      base-url: ${AI_BASE_URL}
      model-name: ${EMBEDDING_MODEL}

milvus:
  host: ${MILVUS_HOST}
  port: ${MILVUS_PORT}
  username: ${MILVUS_USERNAME}
  password: ${MILVUS_PASSWORD}
  database-name: kaleido
  collection-name: test
  dimension: 1536
